spring:
  profiles:
    active: development
  datasource:
    url: jdbc:h2:mem:spring2023
    username: admin
    password: admin
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

server:
  port: 1111
---
spring:
  config:
    activate:
      on-profile: development
---
spring:
  config:
    activate:
      on-profile: test
  sql:
    init:
      platform: h2
      data-locations: classpath:data-h2.sql
      mode: always
